### ISSUE TITLE
README supports dynamic documentation

### ISSUE THREAD

**Issue by alvyn279** [alvyn279/aws-cdk-billing-alarm#8]
### Context
`jsii` has a really cool feature where the example Typescript code in README is transformed into the target language at package/publish time. This mean NPM and PyPi will respectively show working TS and Python code examples. 

We need to play around that to ensure coherent installation steps and code samples are shown in the packages homepages.

### Tasks
- [x] Remove `Typescript` header
- [x] Have both `npm` and `pip` install 
- [ ] GitHub README will still show default README, so we need to include a statement for specific python example

### Alternatives
Have both TS and Python install/code samples. Will clutter README.

### Notes
N/A

**Comment by alvyn279** [comment]
re-opening because I missed the last step.
